src/CarRental/CarRental.MVC/Areas/CarOwner/Controllers/CarsController.cs
using AutoMapper;
using CarRental.Core.Common;
using CarRental.Core.Models;
using CarRental.Core.ViewModels;
using CarRental.DataAccess.Infrastructure;
using CarRental.DataAccess.Repositories;
using CarRental.MVC.Areas.CarOwner.Models;
using DocumentFormat.OpenXml.InkML;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;



namespace CarRental.MVC.Areas.CarOwner.Controllers
{
    [Area("CarOwner")]
    [Authorize(Roles = "CarOwner")]
    public class CarsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _host;
        private readonly ICarRepository _carRepository;

        public CarsController(
            IUnitOfWork unitOfWork,
            UserManager<ApplicationUser> userManager,
            IMapper mapper,
            IWebHostEnvironment host)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _mapper = mapper;
            _host = host;
            _carRepository = _unitOfWork.GetCarRepository();
        }

        public async Task<IActionResult> Report(string filter = "All")
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var feedbacks = await _carRepository.GetFeedbacksByStar(filter, currentUser);

            var reports = _mapper.Map<List<ReportViewModel>>(feedbacks);
            for (int i = 0; i < feedbacks.Count; i++)
            {
                reports[i].CarImage = feedbacks[i].Booking.Car.CarImages.First(x => x.Description == "right").Url;
            }
            if (reports.Count != 0)
            {
                var averageRating = reports.Select(x => x.Ratings).Average();
                ViewBag.Stars = ((int)averageRating);
            }
            ViewBag.Filter = filter;
            ViewBag.AverageRating = _carRepository.GetAverageStarForUser(currentUser).ToString("#,#");

            return View(reports);
        }

        [HttpPost]
        public async Task<IActionResult> StopRenting(string carId)
        {
            var car = await _unitOfWork.GetRepository<Car>()
                .FirstOrDefaultInclude(x => x.Id == Guid.Parse(carId), includeProps: "Bookings");

            if (car != null)
            {
                if (car.Bookings.Any(x => x.Status != BookingStatus.Completed))
                {
                    TempData["error"] = "Stop renting car failled! Car have at least one booking hasn't finished.";
                    return Json(new { success = true, message = "Car have at least one booking hasn't finished." });
                }
                else
                {
                    car.IsStopRent = true;

                    // Lưu thay đổi vào cơ sở dữ liệu
                    _unitOfWork.GetRepository<Car>().Update(car);
                    await _unitOfWork.SaveChanges();
                    TempData["success"] = "Stop renting car sucessfully!";

                    // Trả về một thông báo hoặc dữ liệu JSON nếu cần
                    return Json(new { success = true, message = "Car rental stopped successfully." });
                }
            }

            // Trả về một thông báo hoặc dữ liệu JSON nếu có lỗi
            return Json(new { success = false, message = "Car not found." });
        }

        [HttpPost]
        public async Task<IActionResult> ContinueAvailable(string carId)
        {
            var car = await _unitOfWork.GetRepository<Car>()
                .FirstOrDefaultInclude(x => x.Id == Guid.Parse(carId), includeProps: "Bookings");

            if (car != null)
            {

                car.IsStopRent = false;

                // Lưu thay đổi vào cơ sở dữ liệu
                _unitOfWork.GetRepository<Car>().Update(car);
                await _unitOfWork.SaveChanges();
                TempData["success"] = "Continue available car sucessfully!";

                // Trả về một thông báo hoặc dữ liệu JSON nếu cần
                return Json(new { success = true, message = "Continue availble car sucessfully!" });
            }

            // Trả về một thông báo hoặc dữ liệu JSON nếu có lỗi
            return Json(new { success = false, message = "Car not found." });
        }



        // GET: CarOwner/Cars
        public async Task<IActionResult> Index()
        {
            // Get the current user
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser == null)
            {
                // User is not authenticated
                return RedirectToAction("Login", "Account"); // Redirect to login page or handle as needed
            }
            var cars = await _unitOfWork
                .GetRepository<Car>()
                .GetQuery()
                .Where(x => x.CarOwnerId == currentUser.Id)
                .Include(x => x.Address)
                .Include(x => x.CarOwner)
                .Include(x => x.CarImages)
                .Include(x => x.Bookings)
                .ThenInclude(x => x.Feedback)
                .ToListAsync();
            return View(cars);
        }



        /// <summary>
        /// Sorting cars
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> SortCars(string selectedOption, int page = 1, int pageSize = 3)
        {
            var currentUser = await _userManager.GetUserAsync(User);



            IEnumerable<CarRental.Core.Models.Car> sortedCars = null;

            // Depending on the selected option, sort the cars
            if (selectedOption == "Newest to lastest")
            {
                sortedCars = await _unitOfWork
                    .GetRepository<Car>()
                    .GetQuery()
                    .Where(x => x.CarOwnerId == currentUser.Id) // Compare with currentUser.Id
                    .OrderByDescending(x => x.CreatedAt)
                    .Include(x => x.Address)
                    .Include(x => x.CarOwner)
                    .Include(x => x.CarImages)
                    .Include(x => x.Bookings)
                    .ThenInclude(x => x.Feedback)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToListAsync();
            }
            else if (selectedOption == "Lastest to newest")
            {
                sortedCars = await _unitOfWork
                    .GetRepository<Car>()
                    .GetQuery()
                    .Where(x => x.CarOwnerId == currentUser.Id)
                    .OrderByDescending(x => x.ProductionYear) // Compare with currentUser.Id
                    .Include(x => x.CarOwner)
                    .Include(x => x.CarImages)
                    .Include(x => x.Address)
                    .Include(x => x.Bookings)
                    .ThenInclude(x => x.Feedback)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .ToListAsync();
            }



            // Render a partial view with the sorted data
            return PartialView("_CarListPartial", sortedCars);
        }


        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarViewModel carViewModel)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var car = await _carRepository.CreateCar(carViewModel, currentUser, _mapper);

            if (car == null)
            {
                return NotFound();
            }

            List<CarImage> carImages = new List<CarImage>()
            {
                UploadCarImage(carViewModel.ImageFileUploadCertificate,CarImagePosition.Certificate, car),
                UploadCarImage(carViewModel.ImageFileUploadRegistration,CarImagePosition.Registration, car),
                UploadCarImage(carViewModel.ImageFileUploadInsurance,CarImagePosition.Insurance, car),
                UploadCarImage(carViewModel.ImageFileUploadFront,CarImagePosition.Front, car),
                UploadCarImage(carViewModel.ImageFileUploadBack,CarImagePosition.Back, car),
                UploadCarImage(carViewModel.ImageFileUploadLeft,CarImagePosition.Left, car),
                UploadCarImage(carViewModel.ImageFileUploadRight,CarImagePosition.Right, car),
            };

            await _unitOfWork.GetRepository<Car>().Insert(car);
            await _unitOfWork.GetRepository<CarImage>().Insert(carImages.ToArray());
            await _unitOfWork.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("CarOwner/Cars/Edit/{carId:guid}")]
        public async Task<IActionResult> Edit(Guid carId)
        {
            var car = await _unitOfWork.GetRepository<Car>()
                .FirstOrDefaultInclude(filter: x => x.Id == carId,
                    includeProps: "Address,CarOwner,BrandModel,CarImages,Bookings");

            var query = _unitOfWork.GetRepository<Car>().GetQuery()
                           .Include(x => x.CarImages)
                           .Include(x => x.Address)
                           .Include(x => x.Bookings)
                           .ThenInclude(x => x.Feedback)
                           .FirstOrDefault(x => x.Id == carId);

            var bookingCount = _unitOfWork.GetRepository<Booking>()
                .GetQuery()
                .Count(b => b.CarId == carId);


src/CarRental/CarRental.MVC/Areas/CarOwner/Controllers/HomeController.cs
using CarRental.Core.Common;
using CarRental.DataAccess.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarRental.MVC.Areas.CarOwner.Controllers
{
    [Area("CarOwner")]
    [Authorize(Roles = AppRoles.CarOwner)]
    public class HomeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public HomeController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        
    }
}

src/CarRental/CarRental.MVC/Areas/Customer/Controllers/HomeController.cs
using CarRental.Core.Common;
using CarRental.Core.Models;
using CarRental.DataAccess.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRental.MVC.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = AppRoles.Customer)]
    public class HomeController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var topCitiesBooking = await _unitOfWork.GetRepository<Address>()
                .GetQuery()
                .Include(x => x.Cars)
                .ThenInclude(x => x.Bookings)
                .SelectMany(address => address.Cars.SelectMany(car => car.Bookings),
                    (address, booking) => new { address.City, BookingCount = 1 })
                .GroupBy(x => x.City)
                .Select(group => new
                {
                    City = group.Key,
                    TotalBookings = group.Sum(x => x.BookingCount)
                })
                .OrderByDescending(x => x.TotalBookings)
                .Take(6)
                .ToListAsync();

            // Check if top cities list is less than 6, if less than 6, filter randomly rest of cities
            if (topCitiesBooking.Count < 6)
            {
                var additionalCities = await _unitOfWork.GetRepository<Address>()
                    .GetQuery()
                    .Where(x => !topCitiesBooking.Select(c => c.City).Contains(x.City))
                    .Select(x => new
                    {
                        City = x.City,
                        TotalBookings = 0
                    })
                    .ToListAsync();

                topCitiesBooking.AddRange(additionalCities);
            }

            // Ensure to have exactly 6 results
            topCitiesBooking = topCitiesBooking.Take(6).ToList();

            ViewBag.TopCitiesBooking = topCitiesBooking;    

            // Feedback
            var feedback = await _unitOfWork.GetRepository<Feedback>()
                .GetQuery()
                .Include(x => x.Booking)
                .Take(6)
                .ToListAsync();
            ViewBag.Feedback = feedback;

            return View();
        }
    }
}

src/CarRental/CarRental.MVC/Controllers/HomeController.cs
using CarRental.Core.Models;
using CarRental.DataAccess.Infrastructure;
using CarRental.MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CarRental.MVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;
		private readonly IUnitOfWork _unitOfWork;

		public HomeController(ILogger<HomeController> logger, IUnitOfWork unitOfWork)
		{
			_logger = logger;
			_unitOfWork = unitOfWork;
		}
		[AllowAnonymous]
		public async Task<IActionResult> Index()
        {
            var topCitiesBooking = await _unitOfWork.GetRepository<Address>()
                .GetQuery()
                .Include(x => x.Cars)
                .ThenInclude(x => x.Bookings)
                .SelectMany(address => address.Cars.SelectMany(car => car.Bookings),
                    (address, booking) => new { address.City, BookingCount = 1 })
                .GroupBy(x => x.City)
                .Select(group => new
                {
                    City = group.Key,
                    TotalBookings = group.Sum(x => x.BookingCount)
                })
                .OrderByDescending(x => x.TotalBookings)
                .Take(6)
                .ToListAsync();

            // Check if top cities list is less than 6, if less than 6, filter randomly rest of cities
            if (topCitiesBooking.Count < 6)
            {
                var additionalCities = await _unitOfWork.GetRepository<Address>()
                    .GetQuery()
                    .Where(x => !topCitiesBooking.Select(c => c.City).Contains(x.City))
                    .Select(x => new
                    {
                        City = x.City,
                        TotalBookings = 0
                    })
                    .ToListAsync();

                topCitiesBooking.AddRange(additionalCities);
            }

            // Ensure to have exactly 6 results
            topCitiesBooking = topCitiesBooking.Take(6).ToList();

            ViewBag.TopCitiesBooking = topCitiesBooking;

            // Feedback
            var feedback = await _unitOfWork.GetRepository<Feedback>()
                .GetQuery()
                .Include(x => x.Booking)
                .Take(6)
                .ToListAsync();
            ViewBag.Feedback = feedback;

            return View();
        }

		public IActionResult AboutUs()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

src/CarRental/CarRental.MVC/Areas/CarOwner/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Car Owner";
}

<div class="container-fluid bg-light">
    <div class="container bg-light bg-custom">
        <div class="row choose_1 mt-5">
            <h1 class="text-black mb-5">Have a car for rent? Don't miss out of your benefit</h1>
            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    <div class="items d-flex justify-content-center align-items-center" style="width: 40px; height: 40px; border: thin solid #000;">
                        <i class="fas fa-usd" style="font-size: 20px;"></i>
                    </div>
                    <div class="d-flex flex-column align-items-center" style="padding-left: 10px;">
                        <h5 class="text-black mb-0">How the insurance works</h5>
                    </div>
                </div>
                <p class="mt-3">From the minute you hand the keys over till the second you get them back you are covered. Your private insurance is not affected </p>

            </div>
            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    <div class="items d-flex justify-content-center align-items-center" style="width: 40px; height: 40px; border: thin solid #000;">
                        <i class="fas fa-shield-alt" style="font-size: 20px;"></i>
                    </div>
                    <div class="d-flex flex-column align-items-center" style="padding-left: 10px;">
                        <h5 class="text-black mb-0">It's completely free</h5>
                    </div>
                </div>
                <p class="mt-3">We offer both owners and renters free sign ups. It's only once a vehicle is rented out that a share is deducted to cover admin and insurance.</p>

            </div>

            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    <div class="items d-flex justify-content-center align-items-center" style="width: 40px; height: 40px; border: thin solid #000;">
                        <i class="far fa-check-circle" style="font-size: 20px;"></i>
                    </div>
                    <div class="d-flex flex-column align-items-center" style="padding-left: 10px;">
                        <h5 class="text-black mb-0">You decided the price</h5>
                    </div>
                </div>
                <p class="mt-3">When you list a car you decide the price. We can help with recommendations as to price, but ultimately you decide!</p>

            </div>
        </div>
        <div class="row choose_1 mt-5">
            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    <div class="items d-flex justify-content-center align-items-center" style="width: 40px; height: 40px; border: thin solid #000;">
                        <i class="fas fa-car" style="font-size: 20px;"></i>
                    </div>
                    <div class="d-flex flex-column align-items-center" style="padding-left: 10px;">
                        <h5 class="text-black mb-0">Handling over over your vehicle </h5>
                    </div>
                </div>
                <p class="mt-3">You arrange the time and location for the exchange of your vehicle with the renter. Both parties will need to agree and sign the vehicle rental sheet before and after key handover.</p>

            </div>
            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    <div class="items d-flex justify-content-center align-items-center" style="width: 40px; height: 40px; border: thin solid #000;">
                        <i class="fas fa-exclamation-triangle" style="font-size: 20px;"></i>
                    </div>
                    <div class="d-flex flex-column align-items-center" style="padding-left: 10px;">
                        <h5 class="text-black mb-0">Your are in charge</h5>
                    </div>
                </div>
                <p class="mt-3">All renters are pre-screened by us to ensure safety and get your approval, if you do not feel comfortable with someone, you are able to decline a booking.</p>

            </div>
            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    <div class="items d-flex justify-content-center align-items-center" style="width: 40px; height: 40px; border: thin solid #000;">
                        <i class="far fa-credit-card" style="font-size: 20px;"></i>
                    </div>
                    <div class="d-flex flex-column align-items-center" style="padding-left: 10px;">
                        <h5 class="text-black mb-0">Set payment</h5>
                    </div>
                </div>
                <p class="mt-3">We pay you once a month and you can always view how much your car has earned under your user profile.</p>

            </div>
        </div>
    </div>
</div>



<section class="mt-5 text-center">
    <div class="container">
        <div class="text-start">
            <h2>Make money on your car right away</h2>
        </div>
        <a class="btn btn-primary mt-5 mb-5" asp-action="Index" asp-controller="Cars" asp-area="CarOwner">List Your Car Today</a>
    </div>
</section>